;; Max flow algorithm to model traffic of the streets in a city.

;; Instead of the max flow algorithm, which finds the optimal flows for each vertex in the street graph, we could try to solve the problem differently. We could try a "distributed" algorithm, that tries to select the street that should be taken according to the following: 1. if a car is in a street, it drives with its preferred speed along the street 2. if a car arrives at a junction it selects one of the other streets connected to this junction by applying function #'SELECT. #'SELECT receives a list of outgoing streets, where each outgoing street has the following parameters: 1. length of the street 2. capacity of the street (number of outgoing lanes) 3. current flow in the outgoing lane 4. minimal distance between the end of the outgoing street (i.e. the next junction if the car selects this outgoing street) and the target of the car. #'SELECT returns the street that the car should take. #'SELECT could also output a list of probabilities with which the car should take each street.

;; The Goldberg-Rao max-flow-algorithm talks about strongly connected components. This gave me the idea of letting the player define pedestrian areas, within which no car is allowed and all transportation inside is done by foot. In the max-flow algorithm the pedestrian area is considered as a single node, and the cut of the pedestrian area with the former street network defines the edges to and from this new pedestrian-area-node. In the late-game, this could reduce the computation time of the max-flow-algorithm.

;; There will be police cars, firetrucks, and ambulances racing through the city and if they cannot reach their destination in time it will have consequences for the player. For example a fire will start, the health of the citizens will decrease, or crime will increase in the unreached destination.

;; Each citizen will need one or many income sources (i.e. jobs), a market or supermarket where they can get food and other products from, a house where they sleep, once in a while (preferably on weekends) a recreational trip to a "green" area (distant via railway/airplane/autobahn or local parks). There there will be industrial areas (for products), food production areas (for food), commercial areas (for markets, supermarkets, and general stores), housing areas (for huts, tents, houses, skyscrapers where citizens can build and own or rent a flat), they will own money, have spouses and kids, there will be schools where kids go to every day. Paths across heavily car-frequented streets inreases the probability of an accident which will spawn a police car and ambulance. From time to time, there will be a demonstration, which will block traffic on some streets completely. From time to time, a very important person (VIP) will have to be transferred from point A to point B in the city (for example from the airport to a hotel in the city center), and the player must provide a routing through the streets with little crime, and traffic in these streets will be blocked for the duration of the travel. There may be demonstrations against the VIP, blocking further streets near the route. From time to time, there may be non-orderly demonstrations lasting longer than a day, blocking places (including intersections and their streets in the city center).
