/*library of built-in functions for programs generated by lispccompiler.lisp*/

void inline plus_int_int(int a, int b, int* r) {
	*r = a+b;
}
void inline plus_float_float(float a, float b, float* r) {
	*r = a+b;
}
void inline multiply_int_int(int a, int b, int* r) {
	*r = a*b;
}
void inline multiply_float_float(float a, float b, float* r) {
	*r = a*b;
}
void inline minus_int_int(int a, int b, int* r) {
	*r = a-b;
}
void inline minus_float_float(float a, float b, float* r) {
	*r = a-b;
}
void inline plusone_int (int a, int* r) {
	*r = a+1;
}
void inline plusone_float (float a, float* r) {
	*r = a+1;
}
void inline minusone_int (int a, int* r) {
	*r = a-1;
}
void inline minusone_float (float a, float* r) {
	*r = a-1;
}
void inline print_int(int a) {
	printf("%i",a);
}
void inline less_int_int(int a, int b, int* r) {
	*r = a<b;
}
void inline lessequal_int_int(int a, int b, int* r) {
	*r = a<=b;
}
void inline greater_int_int(int a, int b, int* r) {
	*r = a>b;
}
void inline greaterequal_int_int(int a, int b, int* r) {
	*r = a>=b;
}
void inline equal_int_int(int a, int b, int* r) {
	*r = a==b;
}
